app.py
from flask import Flask,render_template,session
import json
from blueprint_query.query import blueprint_query
from blueprint_auth.auth import blueprint_auth
from blueprint_report.report import blueprint_report
from blueprint_unload.unload import blueprint_unload





app = Flask(__name__, template_folder='templates')
app.secret_key = 'A vot i moi secretniy cluch'

app.register_blueprint(blueprint_query, url_prefix='/query')
app.register_blueprint(blueprint_auth, url_prefix='/auth')
app.register_blueprint(blueprint_report, url_prefix='/report')
app.register_blueprint(blueprint_unload, url_prefix='/unload')



with open('jsonFile/db_config.json') as f:
    app.config['db_config'] = json.load(f)

with open('jsonFile/access.json') as f:
    app.config['access_config'] = json.load(f)

with open('jsonFile/reports.json') as f:
    app.config['report_config'] = json.load(f)



@app.route('/')
def main_menu_auth():
    return render_template("main_menu_auth.html")


@app.route('/main')
def main_menu():
    return render_template("main_menu.html")



if __name__ == '__main__':
    app.run(host='127.0.0.1', port=5001, debug=True)

blueprint_auth/auth.py
import os
from flask import Blueprint, render_template, request, current_app, session
from DB.work_with_db import select_dict
from DB.sql_provider import SQLProvider



blueprint_auth = Blueprint('bp_auth', __name__, template_folder='templates', static_folder='static')
provider = SQLProvider(os.path.join(os.path.dirname(__file__), 'sql'))


@blueprint_auth.route('/', methods=["GET", "POST"])
def authorization():
    if request.method == 'GET':
        return render_template('authorization.html')
    else:
        login = request.form.get('login')
        password = request.form.get('password')
        _sql = provider.get('login_in.sql', login=login, password=password)
        enter = select_dict(current_app.config['db_config'], _sql)
        if enter:
            session['user_id'] = enter[0]['user_id']
            session['user_group'] = enter[0]['group_name']
            return render_template("main_menu.html")
        else:
            _sql = provider.get('login_g.sql', login=login, password=password)
            enter = select_dict(current_app.config['db_config'], _sql)
            if enter:
                session['user_id'] = enter[0]['user_id']
                session['user_group'] = "noname"
                return render_template("main_menu.html")
            else:
                return render_template('authorization.html', error="Неверный логин или пароль!")


@blueprint_auth.route('/', methods=['GET', 'POST'])
def sign_out():
    session.clear()
    return render_template('main_menu_auth.html.html')

templates/main_menu.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Main menu</title>
    <style>
        body {
            text-align: center;
            padding: 20px;
            font-family: 'Arial', sans-serif;
            background-color: #f8f9fa;
        }

        h2 {
            color: #1169ce;
            font-family: 'Arial', sans-serif;
        }

        .container {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
        }

        .image-container {
            margin-top: 20px;
        }

        img {
            border: 1px solid #ddd;
            border-radius: 8px;
            padding: 10px;
            width: 350px;
        }

        .btn-container {
            margin-top: 20px;
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
        }

        .btn {
            margin: 10px;
            padding: 12px 24px;
            font-size: 18px;
            cursor: pointer;
            text-align: center;
            text-decoration: none;
            outline: none;
            color: #fff;
            background-color: #1169ce;
            border: none;
            border-radius: 15px;
            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);
            transition: background-color 0.3s ease;
        }

        .btn:hover {
            background-color: #1169ce;
        }

        .btn:active {
            background-color: #1169ce;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            transform: translateY(4px);
        }
    </style>
</head>

<body>
    <div class="container">
        <h2>Порт</h2>

        <div class="image-container">
            <img src="https://www.eastrussia.ru/upload/blogs/en_2.jpg" height="300px" width="350px" alt="Port Image">
        </div>

    {% if session.get("user_group") == 'admin' %}
        <div class="btn-container">
        <a class="btn" href="{{url_for('bp_query.query_menu')}}">Работа с запросами</a>
        <a class="btn" href="{{url_for('bp_report.work_with_reports')}}">Работа с отчетом</a>
        <a class="btn" href="{{url_for('bp_unload.unload_menu')}}">Создание бригады на разгрузку корабля</a>
        <a class="btn" href="{{url_for('bp_auth.sign_out')}}">Выход из системы</a>
        </div>
    {% elif session.get("user_group") == "manager" %}
        <div class="btn-container">
        <a class="btn" href="{{url_for('bp_report.work_with_reports')}}">Работа с отчетом</a>
        <a class="btn" href="{{url_for('bp_auth.sign_out')}}">Выход из системы</a>
        </div>
    {% elif session.get("user_group") == 'analyst' %}
        <div class="btn-container">
        <a class="btn" href="{{url_for('bp_query.query_menu')}}">Работа с запросами</a>
        <a class="btn" href="{{url_for('bp_auth.sign_out')}}">Выход из системы</a>
        </div>
    {% elif session.get("user_group") == "unload"%}
        <div class="btn-container">
        <a class="btn" href="{{url_for('bp_unload.unload_menu')}}">Создание бригады на разгрузку корабля</a>
        <a class="btn" href="{{url_for('bp_auth.sign_out')}}">Выход из системы</a>
        </div>
    {%elif session.get("user_group") == "noname"%}
        <div class="btn-container">
        <a class="btn" href="{{url_for('bp_query.unloadtable')}}">Расписание разгрузок</a>
        <a class="btn" href="{{url_for('bp_auth.sign_out')}}">Выход из системы</a>
        </div>
    {% endif %}
    {#<p>User Group (from template): {{ session.get("user_group") }}</p>#}
    </div>
</body>

</html>

templates/main_menu_auth.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Main menu</title>
    <style>
        body {
            text-align: center;
            padding: 20px;
            font-family: 'Arial', sans-serif;
            background-color: #f8f9fa;
        }

        h2 {
            color: #1169ce;
            font-family: 'Arial', sans-serif;
        }

        .container {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
        }

        .image-container {
            margin-top: 20px;
        }

        img {
            border: 1px solid #ddd;
            border-radius: 8px;
            padding: 10px;
            width: 350px;
        }

        .btn-container {
            margin-top: 20px;
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
        }

        .btn {
            margin: 10px;
            padding: 12px 24px;
            font-size: 18px;
            cursor: pointer;
            text-align: center;
            text-decoration: none;
            outline: none;
            color: #fff;
            background-color: #1169ce;
            border: none;
            border-radius: 15px;
            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);
            transition: background-color 0.3s ease;
        }

        .btn:hover {
            background-color: #1169ce;
        }

        .btn:active {
            background-color: #1169ce;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            transform: translateY(4px);
        }
                .container {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
        }

    </style>
</head>

<body>
    <div class="container">
        <h2>Порт</h2>

        <div class="image-container">
            <img src="https://www.eastrussia.ru/upload/blogs/en_2.jpg" height="300px" width="350px" alt="Port Image">
        </div>

        <div class="btn-container">
            <a class="btn" href="{{url_for('bp_auth.authorization')}}">Авторизация</a>
{#            <a class="btn" href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" target="_blank">Выход из системы</a>#}
        </div>
    </div>
</body>
</html>

templates/main_new.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Main menu</title>
    <style>
        body {
            text-align: center;
            padding: 20px;
            font-family: 'Arial', sans-serif;
            background-color: #f8f9fa;
        }

        h2 {
            color: #1169ce;
            font-family: 'Arial', sans-serif;
        }

        .container {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
        }

        .image-container {
            margin-top: 20px;
        }

        img {
            border: 1px solid #ddd;
            border-radius: 8px;
            padding: 10px;
            width: 350px;
        }

        .btn-container {
            margin-top: 20px;
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
        }

        .btn {
            margin: 10px;
            padding: 12px 24px;
            font-size: 18px;
            cursor: pointer;
            text-align: center;
            text-decoration: none;
            outline: none;
            color: #fff;
            background-color: #1169ce;
            border: none;
            border-radius: 15px;
            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);
            transition: background-color 0.3s ease;
        }

        .btn:hover {
            background-color: #1169ce;
        }

        .btn:active {
            background-color: #1169ce;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            transform: translateY(4px);
        }
    </style>
</head>

<body>
    <div class="container">
        <h2>Порт</h2>

        <div class="image-container">
            <img src="https://www.eastrussia.ru/upload/blogs/en_2.jpg" height="300px" width="350px" alt="Port Image">
        </div>

    {% if session.get("user_group") == 'admin' %}
        <div class="btn-container">
        <a class="btn" href="{{url_for('bp_query.query_menu')}}">Работа с запросами</a>
        <a class="btn" href="{{url_for('bp_report.work_with_reports')}}">Работа с отчетом</a>
        <a class="btn" href="{{url_for('bp_unload.unload_menu')}}">Создание бригады на разгрузку корабля</a>
        <a class="btn" href="{{url_for('bp_auth.sign_out')}}">Выход из системы</a>
        </div>
    {% elif session.get("user_group") == "manager" %}
        <div class="btn-container">
        <a class="btn" href="{{url_for('bp_query.query_menu')}}">Работа с запросами</a>
        <a class="btn" href="{{url_for('bp_report.work_with_reports')}}">Работа с отчетом</a>
        <a class="btn" href="{{url_for('bp_auth.sign_out')}}">Выход из системы</a>
        </div>
    {% elif session.get("user_group") == "unload manager"%}
        <div class="btn-container">
        <a class="btn" href="{{url_for('bp_unload.unload_menu')}}">Создание бригады на разгрузку корабля</a>
        <a class="btn" href="{{url_for('bp_auth.sign_out')}}">Выход из системы</a>
        </div>
    {%elif session.get("user_group") == "noname"%}
        <div class="btn-container">
        <a class="btn" href="{{url_for('bp_auth.sign_out')}}">Выход из системы</a>
        </div>
    {% endif %}
{#    <p>User Group (from template): {{ session.get("user_group") }}</p>#}
    </div>
</body>

</html>